services:
  nutrislice-menu-widget-api:
    build: .
    container_name: nutrislice-menu-widget-api
    ports:
      - "${PORT:-8080}:8080"
    environment:
      WEB_CONCURRENCY: "2"
      GUNICORN_THREADS: "4"
      APP_TIMEZONE: ${APP_TIMEZONE:-America/Chicago}
      CACHE_TTL_SECONDS: ${CACHE_TTL_SECONDS:-1800}
      NUTRISLICE_ROOT_URL: ${NUTRISLICE_ROOT_URL:-https://district196.api.nutrislice.com/menu/api/weeks/school/echo-park/menu-type/breakfast-lunch/}
